/**
 * Parameters required to calculate net salary and taxes.
 */
export interface TaxCalculationParameters {
    /** Gross monthly salary in Uruguayan pesos */
    grossSalary: number;

    /** Whether the person has children as dependents */
    hasChildren: boolean;

    /** Whether the person has a spouse as a dependent */
    hasSpouse: boolean;

    /**
     * Deduction factor applied to dependents (0, 0.5, or 1).
     * Represents 0%, 50%, or 100% deduction.
     */
    dependentDeductionFactor: number;

    /** Number of children without disabilities */
    childrenWithoutDisability: number;

    /** Number of children with disabilities */
    childrenWithDisability: number;

    /**
     * Solidarity Fund contribution in BPC (e.g., 0.5, 1, 2).
     * Only applies to university professionals.
     */
    solidarityFundContribution: number;

    /** Whether an additional solidarity fund contribution applies (typically for careers ≥ 5 years) */
    additionalSolidarityFund: boolean;

    /** Monthly contribution to CJPPU or Notarial Fund */
    professionalFundContribution: number;

    /** Any other additional deduction (e.g., donations, union dues) */
    otherDeductions: number;
}

/**
 * Represents the mandatory social security contributions deducted from the gross salary.
 */
export interface SocialSecurityContributions {
    /** Retirement (Jubilación) - 15% of salary up to a cap */
    retirement: number;

    /** FONASA (public health contribution) - varies based on dependents and salary */
    health: number;

    /** FRL (training fund) - 0.1% of salary */
    trainingFund: number;
}

/**
 * Detail for each IRPF bracket applied during tax calculation.
 */
export interface IRPFBracketDetail {
    /** Human-readable range label (e.g., "From 15 to 30 BPC") */
    range: string;

    /** Start of the bracket in pesos */
    from: number;

    /** End of the bracket in pesos (null for the last bracket) */
    to: number | null;

    /** Amount from the gross salary that falls within this bracket */
    appliedAmount: number;

    /** IRPF rate (%) applied for this bracket */
    rate: number;

    /** Tax generated by this bracket */
    tax: number;
}

/**
 * Detailed IRPF calculation result.
 */
export interface IRPFDetails {
    /** Breakdown of tax per bracket */
    brackets: IRPFBracketDetail[];

    /** Total amount of applicable deductions */
    deductions: number;

    /** Deduction rate (8% or 14%) depending on income level */
    deductionRate: number;
}

/**
 * IRPF (personal income tax) result, including breakdown and total.
 */
export interface IRPFResult {
    /** Detailed bracket and deduction info */
    details: IRPFDetails;

    /** Total IRPF to be deducted */
    total: number;
}

/**
 * Final result of the tax and salary calculation.
 */
export interface TaxCalculationResult {
    /** Gross salary */
    grossSalary: number;

    /** Final net salary after all deductions */
    netSalary: number;

    /** Retirement contribution amount */
    retirement: number;

    /** Health (FONASA) contribution amount */
    health: number;

    /** Training fund (FRL) contribution amount */
    trainingFund: number;

    /** IRPF breakdown and deduction info */
    irpfDetails: IRPFDetails;

    /** Final IRPF amount to be paid */
    irpfTotal: number;
}